Step 0: Import all relevant libraries used in this project

Step 1: Download crime data related to CTA from the City of Chicago data portal API until November 15, 2019

Step 2: Clean the crime data

Step 3: Create Grid Table based on crime data

Step 4: Assign GridID to crime data

Step 5: Load BusStop and TrainStop data

Step 6: Clean BusStop and TrainStop data

Step 7: Assign GridID to BusStop and TrainStop data

Step 8: Load holiday data

Step 9: Clean holiday data

Step 10: Load tables into CloudSQL

Step 11: Daily refresh of crime data

Step 12: Clean daily updated crime data

Step 13: Assign GridID to daily updated crime data

Step 14: Append daily updated crime data to the crime database in CloudSQL

Import and clean CTA data (for reference of .dbf to .csv transformation, see https://pypi.org/project/simpledbf/; perform $ pip install simpledbf)

In [21]:
# import relevant libraries
import pandas as pd
import dbfread
from simpledbf import Dbf5

Create city grid table to generate unique IDs for all crimes and CTA locations to match data across datasets

In [ ]:
# @Peter: insert code for grid table generation here

In [22]:
# import CTA_BusStops.dbf
# retrieved from GitHub
# originally downloaded from https://data.cityofchicago.org/Transportation/CTA-Bus-Stops-Shapefile/pxug-u72f
dbf1 = Dbf5('Datasets/CTA_BusStops.dbf', codec='utf-8')

In [23]:
# take a look at the file
dbf1.fields

[('DeletionFlag', 'C', 1),
 ('OBJECTID', 'N', 10),
 ('SYSTEMSTOP', 'N', 19),
 ('STREET', 'C', 75),
 ('CROSS_ST', 'C', 75),
 ('DIR', 'C', 3),
 ('POS', 'C', 4),
 ('ROUTESSTPG', 'C', 75),
 ('OWLROUTES', 'C', 20),
 ('CITY', 'C', 20),
 ('STATUS', 'N', 10),
 ('PUBLIC_NAM', 'C', 75),
 ('POINT_X', 'N', 19),
 ('POINT_Y', 'N', 19)]

In [24]:
# export .dbf file to .csv (BusStops)
dbf1.to_csv('Datasets/CTA_BusStops.csv')

In [25]:
# read .csv for BusStops
BusStops = pd.read_csv('Datasets/CTA_BusStops.csv', index_col = 'OBJECTID')

In [26]:
# change column name POINT_X and POINT_Y to lat and long
BusStops = BusStops.rename(columns={"POINT_X": "longitude", "POINT_Y":"latitude"})

In [27]:
# look at clean data frame
BusStops.head()

,SYSTEMSTOP,STREET,CROSS_ST,DIR,POS,ROUTESSTPG,OWLROUTES,CITY,STATUS,PUBLIC_NAM,longitude,latitude
OBJECTID,,,,,,,,,,,,
193,6696.0,TAYLOR,THROOP,EB,NS,157,NaN,CHICAGO,1,Taylor & Throop,-87.659294,41.869314
194,22.0,JACKSON,KARLOV,EB,FS,126,NaN,CHICAGO,1,Jackson & Karlov,-87.727808,41.877007
195,4767.0,FOSTER,MONTICELLO,EB,NS,92,NaN,CHICAGO,1,Foster & Monticello,-87.719780,41.975526
196,6057.0,ASHLAND,CERMAK/BLUE ISLAND,SB,NS,"9,X9",N9,CHICAGO,1,Ashland & Cermak/Blue Island,-87.666173,41.852484
197,1790.0,CLARK,ALBION,SB,NS,22,N22,CHICAGO,1,Clark & Albion,-87.671981,42.001785

In [28]:
# import CTA_TrainStops.csv
# retrieved from GitHub
# originally downloaded from https://data.cityofchicago.org/Transportation/CTA-System-Information-List-of-L-Stops/8pix-ypme
TrainStops = pd.read_csv('Datasets/CTA_TrainStops.csv', index_col = 'STOP_ID')
TrainStops.head()

,DIRECTION_ID,STOP_NAME,STATION_NAME,STATION_DESCRIPTIVE_NAME,MAP_ID,ADA,RED,BLUE,G,BRN,P,Pexp,Y,Pnk,O,Location
STOP_ID,,,,,,,,,,,,,,,,
30162,W,18th (54th/Cermak-bound),18th,18th (Pink Line),40830,True,False,False,False,False,False,False,False,True,False,"(41.857908, -87.669147)"
30161,E,18th (Loop-bound),18th,18th (Pink Line),40830,True,False,False,False,False,False,False,False,True,False,"(41.857908, -87.669147)"
30022,N,35th/Archer (Loop-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,False,False,False,False,False,True,"(41.829353, -87.680622)"
30023,S,35th/Archer (Midway-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,False,False,False,False,False,True,"(41.829353, -87.680622)"
30214,S,35-Bronzeville-IIT (63rd-bound),35th-Bronzeville-IIT,35th-Bronzeville-IIT (Green Line),41120,True,False,False,True,False,False,False,False,False,False,"(41.831677, -87.625826)"

In [29]:
# clean up TrainStations's Location column into Point_X and Point_Y
# split location column
LocationNew = TrainStops["Location"].str.split(",", n = 1, expand = True)
LocationNew.head()

                  0             1
STOP_ID
30162    (41.857908   -87.669147)
30161    (41.857908   -87.669147)
30022    (41.829353   -87.680622)
30023    (41.829353   -87.680622)
30214    (41.831677   -87.625826)

In [30]:
# remove parentheses
LocationNew[0].replace(regex=True,inplace=True,to_replace=r'\(',value=r'')
LocationNew[1].replace(regex=True,inplace=True,to_replace=r'\)',value=r'')
LocationNew.head()

                 0            1
STOP_ID
30162    41.857908   -87.669147
30161    41.857908   -87.669147
30022    41.829353   -87.680622
30023    41.829353   -87.680622
30214    41.831677   -87.625826

In [31]:
# add Point_Y and Point_X to dataframe
TrainStops["latitude"] = LocationNew[0]
TrainStops["longitude"] = LocationNew[1]
TrainStops = TrainStops.drop("Location", 1)

In [32]:
# look at clean data frame
TrainStops.head()

,DIRECTION_ID,STOP_NAME,STATION_NAME,STATION_DESCRIPTIVE_NAME,MAP_ID,ADA,RED,BLUE,G,BRN,P,Pexp,Y,Pnk,O,latitude,longitude
STOP_ID,,,,,,,,,,,,,,,,,
30162,W,18th (54th/Cermak-bound),18th,18th (Pink Line),40830,True,False,False,False,False,False,False,False,True,False,41.857908,-87.669147
30161,E,18th (Loop-bound),18th,18th (Pink Line),40830,True,False,False,False,False,False,False,False,True,False,41.857908,-87.669147
30022,N,35th/Archer (Loop-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,False,False,False,False,False,True,41.829353,-87.680622
30023,S,35th/Archer (Midway-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,False,False,False,False,False,True,41.829353,-87.680622
30214,S,35-Bronzeville-IIT (63rd-bound),35th-Bronzeville-IIT,35th-Bronzeville-IIT (Green Line),41120,True,False,False,True,False,False,False,False,False,False,41.831677,-87.625826

Establish API to crime data and clean it (perform pip install sodapy)

In [35]:
# import requests library
from sodapy import Socrata

In [36]:
# API instructions https://dev.socrata.com/foundry/data.cityofchicago.org/ijzp-q8t2
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
# client = Socrata("data.cityofchicago.org", None)

# Example authenticated client (needed for non-public datasets):
client = Socrata("data.cityofchicago.org",
                  "QtMhXqaTTglPlVS3AC6PEQQxD", username = "juli.kleindiek@gmail.com", password = "DEPA_2019")

# Limit to 6000 rows to avoid time out errors, data has <6000 rows, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("5xiy-qnsz", limit = 6000)

In [37]:
results[1]

{':@computed_region_d9mm_jgwp': '7',
 ':@computed_region_43wa_7qmu': '40',
 'date': '2011-03-20T13:00:00.000',
 'location': {'latitude': '41.913644076',
  'human_address': '{"address": "", "city": "", "state": "", "zip": ""}',
  'needs_recoding': False,
  'longitude': '-87.687306326'},
 'district': '014',
 'y_coordinate': '1911784',
 'block': '017XX N WESTERN AVE',
 ':@computed_region_rpca_8um6': '1',
 'latitude': '41.913644076',
 ':@computed_region_awaf_s7ux': '24',
 'description': 'CREDIT CARD FRAUD',
 'location_description': 'CTA BUS',
 'community_area': '24',
 'updated_on': '2018-02-10T15:50:01.000',
 'iucr': '1150',
 'x_coordinate': '1160086',
 'ward': '1',
 'year': '2011',
 'case_number': 'HT212010',
 'fbi_code': '11',
 'domestic': False,
 'longitude': '-87.687306326',
 ':@computed_region_bdys_3d7i': '298',
 'beat': '1434',
 ':@computed_region_6mkv_f3dw': '22535',
 'arrest': False,
 'primary_type': 'DECEPTIVE PRACTICE',
 ':@computed_region_vrxf_vc4k': '25',
 'id': '7979411',
 ':@computed_region_d3ds_rm58': '192'}

In [38]:
# Convert results to pandas DataFrame
crime_dirty = pd.DataFrame.from_records(results)

In [39]:
crime_dirty.head()

,:@computed_region_43wa_7qmu,:@computed_region_6mkv_f3dw,:@computed_region_awaf_s7ux,:@computed_region_bdys_3d7i,:@computed_region_d3ds_rm58,:@computed_region_d9mm_jgwp,:@computed_region_rpca_8um6,:@computed_region_vrxf_vc4k,arrest,beat,...,latitude,location,location_description,longitude,primary_type,updated_on,ward,x_coordinate,y_coordinate,year
0,36,4452,22,784,91,22,45,29,False,0111,...,41.882189946,"{'latitude': '41.882189946', 'human_address': ...",CTA BUS,-87.641202862,BATTERY,2018-02-10T15:50:01.000,42,1172727,1900420,2011
1,40,22535,24,298,192,7,1,25,False,1434,...,41.913644076,"{'latitude': '41.913644076', 'human_address': ...",CTA BUS,-87.687306326,DECEPTIVE PRACTICE,2018-02-10T15:50:01.000,1,1160086,1911784,2011
2,14,21569,36,772,153,21,57,30,False,1021,...,41.859020037,"{'latitude': '41.859020037', 'human_address': ...",CTA BUS,-87.710681986,THEFT,2018-02-10T15:50:01.000,24,1153868,1891832,2011
3,13,21554,18,531,233,20,59,70,False,0613,...,41.735931109,"{'latitude': '41.735931109', 'human_address': ...",CTA BUS,-87.653642482,THEFT,2018-02-10T15:50:01.000,21,1169761,1847097,2011
4,1,21569,14,261,130,21,57,32,False,1033,...,41.847153749,"{'latitude': '41.847153749', 'human_address': ...",CTA BUS,-87.70511925,ROBBERY,2018-02-10T15:50:01.000,24,1155415,1887519,2011

In [40]:
# investigate crime_dirty
crime_dirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5808 entries, 0 to 5807
Data columns (total 30 columns):
:@computed_region_43wa_7qmu    5803 non-null object
:@computed_region_6mkv_f3dw    5806 non-null object
:@computed_region_awaf_s7ux    5803 non-null object
:@computed_region_bdys_3d7i    5790 non-null object
:@computed_region_d3ds_rm58    5803 non-null object
:@computed_region_d9mm_jgwp    5803 non-null object
:@computed_region_rpca_8um6    5803 non-null object
:@computed_region_vrxf_vc4k    5803 non-null object
arrest                         5808 non-null bool
beat                           5808 non-null object
block                          5808 non-null object
case_number                    5808 non-null object
community_area                 5808 non-null object
date                           5808 non-null object
description                    5808 non-null object
district                       5808 non-null object
domestic                       5808 non-null bool
fbi_code                       5808 non-null object
id                             5808 non-null object
iucr                           5808 non-null object
latitude                       5806 non-null object
location                       5806 non-null object
location_description           5808 non-null object
longitude                      5806 non-null object
primary_type                   5808 non-null object
updated_on                     5808 non-null object
ward                           5808 non-null object
x_coordinate                   5806 non-null object
y_coordinate                   5806 non-null object
year                           5808 non-null object
dtypes: bool(2), object(28)
memory usage: 1.3+ MB

In [41]:
# validate the values , i.e. 'id'
crime_dirty.loc[2:3]['id']

2    7981270
3    7979660
Name: id, dtype: object

In [42]:
# bring dataframe into proper format
crime = crime_dirty[['id', 
        'case_number', 
        'date', 
        'block', 
        'iucr', 
        'primary_type', 
        'description', 
        'location_description',
        'arrest',
        'domestic',
        'beat',
        'district',
        'ward',
        'community_area',
        'fbi_code',
        'x_coordinate',
        'y_coordinate',
        'year',
        'updated_on',
        'latitude',
        'longitude']]

In [43]:
# take a look at the proper dataframe
crime.head()

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,district,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude
0,8256302,HT490196,2011-09-10T12:46:00.000,0000X N CLINTON ST,0460,BATTERY,SIMPLE,CTA BUS,False,False,...,001,42,28,08B,1172727,1900420,2011,2018-02-10T15:50:01.000,41.882189946,-87.641202862
1,7979411,HT212010,2011-03-20T13:00:00.000,017XX N WESTERN AVE,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,CTA BUS,False,False,...,014,1,24,11,1160086,1911784,2011,2018-02-10T15:50:01.000,41.913644076,-87.687306326
2,7981270,HT213521,2011-03-20T15:00:00.000,034XX W 16TH ST,0820,THEFT,$500 AND UNDER,CTA BUS,False,False,...,010,24,29,06,1153868,1891832,2011,2018-02-10T15:50:01.000,41.859020037,-87.710681986
3,7979660,HT212325,2011-03-20T20:09:00.000,012XX W 87TH ST,0820,THEFT,$500 AND UNDER,CTA BUS,False,False,...,006,21,71,06,1169761,1847097,2011,2018-02-10T15:50:01.000,41.735931109,-87.653642482
4,7989927,HT213271,2011-03-20T20:57:00.000,024XX S KEDZIE AVE,033A,ROBBERY,ATTEMPT: ARMED-HANDGUN,CTA BUS,False,False,...,010,24,30,03,1155415,1887519,2011,2018-02-10T15:50:01.000,41.847153749,-87.70511925

In [44]:
# rename column 'id' into 'crimeID'
crime = crime.rename(columns={"id": "crimeID"})

In [45]:
# define proper data types for each column; WE NEED FURTHER CLEANING HERE
crime = crime.astype({"crimeID": int})

In [46]:
# set index of crime dataframe to 'id'
crime.set_index('crimeID')

,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,beat,district,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude
crimeID,,,,,,,,,,,,,,,,,,,,
8256302,HT490196,2011-09-10T12:46:00.000,0000X N CLINTON ST,0460,BATTERY,SIMPLE,CTA BUS,False,False,0111,001,42,28,08B,1172727,1900420,2011,2018-02-10T15:50:01.000,41.882189946,-87.641202862
7979411,HT212010,2011-03-20T13:00:00.000,017XX N WESTERN AVE,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,CTA BUS,False,False,1434,014,1,24,11,1160086,1911784,2011,2018-02-10T15:50:01.000,41.913644076,-87.687306326
7981270,HT213521,2011-03-20T15:00:00.000,034XX W 16TH ST,0820,THEFT,$500 AND UNDER,CTA BUS,False,False,1021,010,24,29,06,1153868,1891832,2011,2018-02-10T15:50:01.000,41.859020037,-87.710681986
7979660,HT212325,2011-03-20T20:09:00.000,012XX W 87TH ST,0820,THEFT,$500 AND UNDER,CTA BUS,False,False,0613,006,21,71,06,1169761,1847097,2011,2018-02-10T15:50:01.000,41.735931109,-87.653642482
7989927,HT213271,2011-03-20T20:57:00.000,024XX S KEDZIE AVE,033A,ROBBERY,ATTEMPT: ARMED-HANDGUN,CTA BUS,False,False,1033,010,24,30,03,1155415,1887519,2011,2018-02-10T15:50:01.000,41.847153749,-87.70511925
8332454,HT566424,2011-10-30T09:00:00.000,067XX S HALSTED ST,0460,BATTERY,SIMPLE,CTA BUS,False,False,0723,007,6,68,08B,1172128,1860266,2011,2018-02-10T15:50:01.000,41.772016903,-87.64458443
8332084,HT566137,2011-10-30T02:08:00.000,0000X W 95TH ST,0560,ASSAULT,SIMPLE,CTA BUS,True,False,0634,006,21,49,08A,1177762,1841949,2011,2016-02-04T06:33:39.000,41.721627204,-87.624485177
7905059,HT134917,2011-01-25T14:30:00.000,047XX S WENTWORTH AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,CTA BUS,False,True,0231,002,3,37,08B,1175752,1873657,2011,2016-02-04T06:33:39.000,41.808682769,-87.630898966
7906391,HT136142,2011-01-25T15:00:00.000,027XX W DIVISION ST,0560,ASSAULT,SIMPLE,CTA BUS,False,False,1423,014,26,24,08A,1157903,1907866,2011,2016-02-04T06:33:39.000,41.902937604,-87.695433299
7982963,HT214882,2011-03-21T14:30:00.000,107XX S COTTAGE GROVE AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,0513,005,9,50,06,1182249,1833965,2011,2018-02-10T15:50:01.000,41.699615536,-87.60829647
7908516,HT137954,2011-01-25T15:00:00.000,018XX E 75TH ST,0460,BATTERY,SIMPLE,CTA BUS,False,False,0324,003,8,43,08B,1189797,1855610,2011,2016-02-04T06:33:39.000,41.758833905,-87.579965641
7981295,HT213619,2011-03-21T17:35:00.000,028XX N PULASKI RD,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,2523,025,31,21,06,1149239,1918396,2011,2018-02-10T15:50:01.000,41.932005294,-87.726984558
8331651,HT565471,2011-10-29T15:29:00.000,004XX S CENTRAL AVE,0484,BATTERY,PRO EMP HANDS NO/MIN INJURY,CTA BUS,False,False,1513,015,29,25,08B,1139129,1897372,2011,2018-02-10T15:50:01.000,41.874503125,-87.764650028
7986020,HT217594,2011-03-21T19:00:00.000,001XX N STATE ST,0810,THEFT,OVER $500,CTA BUS,False,False,0122,001,42,32,06,1176329,1901689,2011,2018-02-10T15:50:01.000,41.885591676,-87.627938154
7869656,HT100245,2011-01-01T02:50:00.000,015XX W CHICAGO AVE,0460,BATTERY,SIMPLE,CTA BUS,False,False,1323,012,1,24,08B,1165806,1905429,2011,2016-02-04T06:33:39.000,41.896085375,-87.666473716
7907026,HT136391,2011-01-25T17:56:00.000,079XX S LOOMIS BLVD,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,CTA BUS,False,True,0612,006,21,71,26,1168370,1852331,2011,2016-02-04T06:33:39.000,41.750323974,-87.658588247
8413942,HT643325,2011-12-22T12:45:00.000,078XX S ASHLAND AVE,0460,BATTERY,SIMPLE,CTA BUS,False,False,0611,006,17,71,08B,1167038,1852633,2011,2016-02-04T06:33:39.000,41.751181266,-87.663460692
7982740,HT214603,2011-03-22T12:00:00.000,002XX S STATE ST,0460,BATTERY,SIMPLE,CTA BUS,False,False,0123,001,42,32,08B,1176411,1899396,2011,2018-02-10T15:50:01.000,41.879297705,-87.627706271
7878859,HT109220,2011-01-07T12:04:00.000,093XX S COTTAGE GROVE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,CTA BUS,True,False,0633,006,9,44,04B,1183191,1843333,2011,2016-02-04T06:33:39.000,41.725300675,-87.604556978
8394910,HT627849,2011-12-11T20:05:00.000,079XX S VERNON AVE,1330,CRIMINAL TRESPASS,TO LAND,CTA BUS,True,False,0624,006,6,44,26,1180618,1852561,2011,2018-02-10T15:50:01.000,41.750682777,-87.613699222
7992546,HT214874,2011-03-22T14:30:00.000,0000X W 95TH ST,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,0634,006,21,49,06,1177762,1841949,2011,2018-02-10T15:50:01.000,41.721627204,-87.624485177
7879112,HT109461,2011-01-07T13:30:00.000,053XX N MILWAUKEE AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,1622,016,45,11,06,1137759,1934652,2011,2016-02-04T06:33:39.000,41.97682837,-87.768778958
8336007,HT569840,2011-10-29T14:00:00.000,079XX S ST LOUIS AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,0834,008,18,70,06,1154424,1851894,2011,2018-02-10T15:50:01.000,41.749413528,-87.709704762
7905408,HT135572,2011-01-25T20:35:00.000,0000X W 79TH ST,1210,DECEPTIVE PRACTICE,THEFT OF LABOR/SERVICES,CTA BUS,False,False,0623,006,6,44,11,1177483,1852629,2011,2016-02-04T06:33:39.000,41.750940757,-87.625185222
7983371,HT215337,2011-03-22T19:50:00.000,063XX S INGLESIDE AVE,0560,ASSAULT,SIMPLE,CTA BUS,True,False,0314,003,20,42,08A,1183813,1863264,2011,2018-02-10T15:50:01.000,41.779978918,-87.601657723
7878942,HT109374,2011-01-07T13:47:00.000,008XX N STATE ST,0460,BATTERY,SIMPLE,CTA BUS,True,False,1833,018,42,8,08B,1176203,1906479,2011,2016-02-04T06:33:39.000,41.898738526,-87.628256304
8331626,HT565627,2011-10-29T13:00:00.000,087XX S STATE ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,CTA BUS,False,False,0634,006,21,44,26,1177810,1847135,2011,2018-02-10T15:50:01.000,41.735857166,-87.624152861
7998824,HT225477,2011-03-23T13:40:00.000,047XX S DR MARTIN LUTHER KING JR DR,0460,BATTERY,SIMPLE,CTA BUS,False,False,0224,002,3,38,08B,1179656,1873779,2011,2018-02-10T15:50:01.000,41.808929094,-87.616576329
7985598,HT216290,2011-03-23T14:00:00.000,032XX W JACKSON BLVD,0486,BATTERY,DOMESTIC BATTERY SIMPLE,CTA BUS,False,True,1124,011,28,27,08B,1154928,1898510,2011,2018-02-10T15:50:01.000,41.877324023,-87.706612089
7984685,HT216477,2011-03-23T15:00:00.000,089XX S ASHLAND AVE,051A,ASSAULT,AGGRAVATED: HANDGUN,CTA BUS,True,False,2221,022,21,73,04A,1167241,1845314,2011,2018-02-10T15:50:01.000,41.731092535,-87.662925738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8365807,HT599010,2011-11-19T17:00:00.000,005XX N STATE ST,0870,THEFT,POCKET-PICKING,CTA TRAIN,False,False,1834,018,42,8,06,1176278,1903807,2011,2018-02-10T15:50:01.000,41.891404732,-87.628061509
8286302,HT520437,2011-09-29T21:00:00.000,012XX S STATE ST,0810,THEFT,OVER $500,CTA TRAIN,False,False,0132,001,2,33,06,1176526,1894914,2011,2018-02-10T15:50:01.000,41.866996231,-87.62741936
8042760,HT274890,2011-04-30T23:00:00.000,022XX S WENTWORTH AVE,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,2111,009,25,34,03,1175319,1889687,2011,2018-02-10T15:50:01.000,41.85268013,-87.632007113
8286530,HT520617,2011-09-29T23:42:00.000,005XX S PULASKI RD,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,1132,011,24,26,03,1149812,1897228,2011,2018-02-10T15:50:01.000,41.873907046,-87.725430093
7884268,HT108304,2011-01-06T17:30:00.000,015XX N SEDGWICK ST,0810,THEFT,OVER $500,CTA TRAIN,False,False,1821,018,43,8,06,1173364,1910604,2011,2016-02-04T06:33:39.000,41.910121292,-87.638560993
8041871,HT273697,2011-04-30T20:34:00.000,063XX S ASHLAND AVE,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,0725,007,16,67,03,1166756,1862726,2011,2018-02-10T15:50:01.000,41.778883826,-87.664206366
8287063,HT520928,2011-09-30T08:11:00.000,0000X E ROOSEVELT RD,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,CTA TRAIN,False,False,0132,001,2,32,17,1176818,1895074,2011,2018-02-10T15:50:01.000,41.867428687,-87.626342565
8287777,HT521714,2011-09-30T09:35:00.000,004XX S STATE ST,0820,THEFT,$500 AND UNDER,CTA TRAIN,False,False,0132,001,2,32,06,1176440,1898296,2011,2016-02-04T06:33:39.000,41.876278587,-87.627633
8363496,HT596845,2011-11-19T20:10:00.000,040XX W LAKE ST,0810,THEFT,OVER $500,CTA TRAIN,False,False,1114,011,28,26,06,1149512,1901446,2011,2016-02-04T06:33:39.000,41.885487535,-87.726422045
8050706,HT273724,2011-04-30T20:15:00.000,002XX W 63RD ST,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,0711,007,20,68,03,1175827,1863196,2011,2018-02-10T15:50:01.000,41.779975054,-87.630937377
7901689,HT131816,2011-01-21T01:30:00.000,035XX W ADDISON ST,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,CTA TRAIN,False,False,1732,017,35,16,11,1152334,1923710,2011,2016-02-04T06:33:39.000,41.946526695,-87.715470049
8404754,HT631156,2011-12-13T20:30:00.000,012XX N CLARK ST,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,1821,018,42,8,03,1175314,1908524,2011,2018-02-10T15:50:01.000,41.904370109,-87.631460067
8041693,HT273446,2011-04-30T16:30:00.000,005XX N STATE ST,0810,THEFT,OVER $500,CTA TRAIN,False,False,1834,018,42,8,06,1176278,1903807,2011,2018-02-10T15:50:01.000,41.891404732,-87.628061509
8041382,HT272997,2011-04-30T11:10:00.000,011XX S STATE ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,CTA TRAIN,True,False,0132,001,2,32,18,1176517,1895340,2011,2018-02-10T15:50:01.000,41.868165405,-87.62743954
8041186,HT272757,2011-04-30T05:40:00.000,034XX W BELMONT AVE,0870,THEFT,POCKET-PICKING,CTA TRAIN,False,False,1732,017,35,21,06,1153081,1921071,2011,2018-02-10T15:50:01.000,41.939270274,-87.712794514
8043164,HT275288,2011-04-30T04:00:00.000,001XX E 35TH ST,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,2112,002,3,35,03,1177974,1881827,2011,2018-02-10T15:50:01.000,41.831051803,-87.622501311
8042116,HT272689,2011-04-30T03:15:00.000,009XX W FULLERTON AVE,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,1812,018,43,7,03,1169570,1916141,2011,2018-02-10T15:50:01.000,41.925398601,-87.652337017
8041675,HT273478,2011-04-30T03:00:00.000,032XX N HALSTED ST,0820,THEFT,$500 AND UNDER,CTA TRAIN,False,False,2332,019,44,6,06,1170360,1921560,2011,2018-02-10T15:50:01.000,41.940251326,-87.649275328
8363498,HT596914,2011-11-19T21:10:00.000,008XX N STATE ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,CTA TRAIN,True,False,1832,018,42,8,18,1176223,1905805,2011,2016-02-04T06:33:39.000,41.896888586,-87.628203192
8041066,HT272612,2011-04-30T00:05:00.000,015XX N CLYBOURN AVE,1220,DECEPTIVE PRACTICE,THEFT OF LOST/MISLAID PROP,CTA TRAIN,True,False,1822,018,43,8,11,1170470,1910783,2011,2018-02-10T15:50:01.000,41.910676312,-87.649187069
8041012,HT272533,2011-04-29T23:30:00.000,037XX W 50TH ST,0312,ROBBERY,ARMED:KNIFE/CUTTING INSTRUMENT,CTA TRAIN,False,False,0821,008,14,62,03,1152472,1871216,2011,2018-02-10T15:50:01.000,41.802474721,-87.716349783
7942334,HT175101,2011-02-23T10:15:00.000,001XX W 35TH ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,CTA TRAIN,True,False,0924,009,11,34,18,1175739,1881773,2011,2018-02-10T15:50:01.000,41.830954079,-87.630703226
8040503,HT271891,2011-04-29T15:40:00.000,055XX S STATE ST,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,0233,002,3,40,03,1177219,1868295,2011,2018-02-10T15:50:01.000,41.793935909,-87.625680278
8292360,HT525543,2011-09-30T20:00:00.000,002XX S STATE ST,0810,THEFT,OVER $500,CTA TRAIN,False,False,0123,001,42,32,06,1176417,1899156,2011,2018-02-10T15:50:01.000,41.878638996,-87.627691486
7970249,HT202834,2011-02-23T10:00:00.000,075XX N PAULINA AVE,0810,THEFT,OVER $500,CTA TRAIN,False,False,2422,024,49,1,06,1163690,1950023,2011,2018-02-10T15:50:01.000,42.018498254,-87.672983233
8367340,HT600468,2011-11-20T02:30:00.000,011XX W THORNDALE AVE,0820,THEFT,$500 AND UNDER,CTA TRAIN,False,False,2433,024,48,77,06,1167594,1939683,2011,2018-02-10T15:50:01.000,41.990041584,-87.65891695
8363919,HT597395,2011-11-20T03:56:00.000,004XX S DAMEN AVE,0870,THEFT,POCKET-PICKING,CTA TRAIN,False,False,1211,012,2,28,06,1163135,1897829,2011,2018-02-10T15:50:01.000,41.875286899,-87.67649739
8288014,HT522073,2011-09-30T21:00:00.000,016XX W LAKE ST,0454,BATTERY,AGG PO HANDS NO/MIN INJURY,CTA TRAIN,True,False,1333,012,27,28,08B,1165537,1901501,2011,2018-02-10T15:50:01.000,41.885312381,-87.667573631
8040839,HT272125,2011-04-29T15:00:00.000,059XX N GLENWOOD AVE,0460,BATTERY,SIMPLE,CTA TRAIN,True,False,2013,020,48,77,08B,1165910,1939379,2011,2018-02-10T15:50:01.000,41.989243623,-87.665119726
8398367,HT631071,2011-12-13T22:05:00.000,033XX W EISENHOWER EXPY OB,0820,THEFT,$500 AND UNDER,CTA TRAIN,False,False,1134,011,24,27,06,1154284,1897399,2011,2016-02-04T06:33:39.000,41.874288203,-87.709006362

Import and clead holiday data

In [ ]:
# @Lola: insert code for loading holiday data

Establie API to weather data

In [ ]:
# @Lola: insert code for for establishing API to weather data

Establish connection to GCP CouldSQL

In [33]:
# import required package
import pyodbc

In [ ]:
# define connection to the server
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=server_name;'
                      'Database=db_name;'
                      'Trusted_Connection=yes;')

In [ ]:
# define cursor
cursor = conn.cursor()

In [ ]:
# examplary query
cursor.execute('SELECT * FROM db_name.Table')